USE [master]
GO

/****** Object:  Database [HOGWARTS]    Script Date: 24/4/2021 02:08:43 ******/
CREATE DATABASE [HOGWARTS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HOGWARTS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HOGWARTS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HOGWARTS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HOGWARTS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HOGWARTS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HOGWARTS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HOGWARTS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HOGWARTS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HOGWARTS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HOGWARTS] SET ARITHABORT OFF 
GO

ALTER DATABASE [HOGWARTS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HOGWARTS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HOGWARTS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HOGWARTS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HOGWARTS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HOGWARTS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HOGWARTS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HOGWARTS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HOGWARTS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HOGWARTS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HOGWARTS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HOGWARTS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HOGWARTS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HOGWARTS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HOGWARTS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HOGWARTS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HOGWARTS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HOGWARTS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HOGWARTS] SET  MULTI_USER 
GO

ALTER DATABASE [HOGWARTS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HOGWARTS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HOGWARTS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HOGWARTS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HOGWARTS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HOGWARTS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HOGWARTS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HOGWARTS] SET  READ_WRITE 
GO

